USE [BoraqDb]
GO

INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A01','Engine Oil Leaks','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A02','Gearbox Oil Leaks','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A03','Engine Condition / Performance','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A04','Coolant / Any Other Oil Leaks','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A05','Exhaust / Intake / Vacuum System','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A06','Front Brake Pads','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A07','Front Brake Disks','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A08','Rear Brake Pads','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A09','Rear Brake Disks','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A10','Steering Joints','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A11','Suspension Joints','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A12','Suspension Struts','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('A14','Other','Engine / Chassis / Underbody',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('B01','Battery Condition Engine Start Test ONLY','Electrical Functions',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('B02','Check for any warning lights','Electrical Functions',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('B03','Horn','Electrical Functions',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('B04','Central Locking','Electrical Functions',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('B05','Air Conditioning','Electrical Functions',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('B06','Wipers & Washers Inc Front, Rear & Headlamps','Electrical Functions',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C01','Side lights','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C02','Stop lights','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C03','Reversing lights','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C04','Number plates','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C05','Indicator / Hazard lights','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C06','Internal lights & functions','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C07','Internal - Other faults','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C08','Internal - Other faults','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('C09','External trims / Roof Assembly','Lighting / Inside Body trims',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('D01','Clutch / Brake / Power Steering Fluid','Levels',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('D04','Screen / Headlmap washer fluid','Levels',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('D05','Coolant & oil level oil check on cluster ONLY','Levels',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('E01','Front left','Tyres / Wheels: Out / Mid / Inn Tread Depts',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('E02','Front right','Tyres / Wheels: Out / Mid / Inn Tread Depts',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('E03','Rear left','Tyres / Wheels: Out / Mid / Inn Tread Depts',null)
INSERT INTO [dbo].[HealthChecks] ([HcCode],[Description],[HcGroup],[Comments]) 
VALUES('E04','Front right','Tyres / Wheels: Out / Mid / Inn Tread Depts',null)



