// <auto-generated />
namespace VideoUpload.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class structure5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(structure5));
        
        string IMigrationMetadata.Id
        {
            get { return "201704180640476_structure5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
